services:
  postgres-db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=google_docs
    ports:
      - "5433:5432"
    volumes:
      - db:/data/postgres
    networks:
      - google
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - google
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
    
  migrate:
    image: migrate/migrate
    networks:
      - google
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres-db:
        condition: service_healthy
    command: ["-path", "./migrations", "-database", "postgres://postgres:1234@postgres:5432/google_docs?sslmode=disable", "up"]

  userservice:
    container_name: user
    build: .
    ports:
      - "1234:1234"
      - "2345:2345"
    networks:
     - google
    depends_on:
      postgres-db:
        condition: service_healthy
      migrate:
        condition: service_started
      redis:
        condition: service_healthy


networks:
  google:

volumes:
  db:
  minio_data:
